name = "resources"
version = "0.1.0"
defaultTargets = ["resources"]
testDriver = "test"

[[require]]
name = "leansqlite"
git = "https://github.com/leanprover/leansqlite"
rev = "v4.33.0"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "v4.33.0"

[[lean_lib]]
name = "Resources"

[[lean_exe]]
name = "resources"
root = "Main"

[[lean_exe]]
name = "test"
root = "Test.Main"
