/**
 * The conformance vectors, run against this client's own codecs and `step`.
 *
 * `conformance/vectors.json` is generated by `resources gen-vectors` from the
 * Lean core's own `step`: each vector is a state the ledger can reach, an event
 * applied to it, and the state that came out, all three as canonical bytes.
 * This file is the bridge between the verified semantics and this unverified
 * port — the only one there is, because a TypeScript re-implementation cannot
 * be proved and can only be asked the same questions and compared byte for
 * byte.
 *
 * A vector passes when, from `stateHex` and `eventHex` decoded here, `step`
 * produces a state that re-encodes to exactly `expectedHex`, hashes to
 * `expectedHash`, refuses exactly the parts `rejected` names, and returns the
 * same changes in the same order. The bytes are the contract: two
 * implementations that agree on every field but one byte of encoding cannot
 * share a checkpoint.
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { beforeAll, describe, expect, it } from 'vitest'
import { step } from './apply'
import {
  CodecError,
  dateCodec,
  decode,
  encode,
  eventCodec,
  stateCodec,
  stringCodec,
} from './codec'
import type { Codec } from './codec'
import { ready, sha256Hex } from './crypto'
import { fromHex, toHex } from './bytes'

/** One vector, exactly as `vectors.json` holds it. */
interface Vector {
  name: string
  description: string
  stateHex: string
  eventHex: string
  expectedHex: string
  expectedHash: string
  changes: { kind: string; id: string }[]
  rejected: number[]
}

const vectorsPath = fileURLToPath(new URL('../../conformance/vectors.json', import.meta.url))
const vectors: Vector[] = JSON.parse(readFileSync(vectorsPath, 'utf8')) as Vector[]

const rejectsPath = fileURLToPath(new URL('../../conformance/rejects.json', import.meta.url))
const rejects: Reject[] = JSON.parse(readFileSync(rejectsPath, 'utf8')) as Reject[]

/** One entry of `rejects.json`: bytes a conforming decoder of `type` has to refuse. */
interface Reject {
  name: string
  description: string
  type: 'nat' | 'int' | 'string' | 'date' | 'state' | 'event'
  hex: string
}

const versionPath = fileURLToPath(new URL('../../conformance/format-version', import.meta.url))
const formatVersion = Number(readFileSync(versionPath, 'utf8').trim())

/**
 * The wire format this port implements.
 *
 * `conformance/format-version` moves in the commit that moves the format — a
 * tag renumbered, a field added to an encoded type, a primitive changed — so a
 * file this client cannot read announces itself here rather than as a hundred
 * unrelated byte mismatches below.
 */
const supportedFormatVersion = 8

/** The key an entity is held under, as `Vectors.changeId` reports it. */
function changeId(c: ReturnType<typeof step>['changes'][number]): string {
  switch (c.kind) {
    case 'realm':
      return c.realm.id
    case 'member':
      return c.member.id
    case 'memberDeleted':
      return c.id
    case 'account':
      return c.account.id
    case 'accountDeleted':
      return c.id
    case 'label':
      return c.label.id
    case 'labelDeleted':
      return c.id
    case 'party':
      return c.party.id
    case 'group':
      return c.group.name
    case 'groupDeleted':
      return c.name
    case 'trip':
      return c.trip.name
    case 'tripDeleted':
      return c.name
    case 'rule':
      return c.rule.id
    case 'ruleDeleted':
      return c.id
    case 'txn':
      return c.txn.id
    case 'txnDeleted':
      return c.id
    case 'budget':
      return c.budget.budget.id
    case 'budgetDeleted':
      return c.id
    case 'invoice':
      return c.invoice.invoice.id
    case 'invoiceDeleted':
      return c.id
    case 'blob':
      return c.blob.file.sha256
    case 'blobDeleted':
      return c.sha
    case 'batch':
      return c.batch.id
    case 'counter':
      return c.name
    case 'fingerprint':
      return c.fp
  }
}

describe('the conformance vectors', () => {
  beforeAll(async () => {
    await ready()
  })

  it('are written in the wire format this port implements', () => {
    expect(formatVersion).toBe(supportedFormatVersion)
  })

  it('ships 223 of them, and none is empty', () => {
    expect(vectors.length).toBe(223)
    for (const v of vectors) {
      expect(v.name).not.toBe('')
      expect(v.stateHex).not.toBe('')
      expect(v.eventHex).not.toBe('')
      expect(v.expectedHash).toHaveLength(64)
    }
  })

  for (const v of vectors) {
    it(v.name, () => {
      const stateBytes = fromHex(v.stateHex)
      const eventBytes = fromHex(v.eventHex)
      expect(stateBytes).not.toBeNull()
      expect(eventBytes).not.toBeNull()
      const before = decode(stateCodec, stateBytes as Uint8Array)
      const event = decode(eventCodec, eventBytes as Uint8Array)

      // The input bytes are canonical too, so decoding and re-encoding them is
      // itself a test of the codec on a state the ledger can actually reach.
      expect(toHex(encode(stateCodec, before))).toBe(v.stateHex)
      expect(toHex(encode(eventCodec, event))).toBe(v.eventHex)

      const out = step(before, event)
      const bytes = encode(stateCodec, out.state)
      expect(toHex(bytes)).toBe(v.expectedHex)
      expect(sha256Hex(bytes)).toBe(v.expectedHash)
      expect(out.rejected).toEqual(v.rejected)
      expect(out.changes.map((c) => ({ kind: c.kind, id: changeId(c) }))).toEqual(v.changes)
    })
  }
})

/* ------------------------------------------------------------------ */
/* The other half: bytes that have to be refused                       */
/* ------------------------------------------------------------------ */

/**
 * `conformance/rejects.json`, run against the decoder each entry names.
 *
 * Every vector above is a well-formed input, so a port could reproduce all of
 * them while accepting bytes no writer produces — and a checkpoint is the hash
 * of a state's canonical encoding, so a reader that takes a second spelling of
 * one state re-encodes it to something the sender never committed to, and two
 * honest peers then disagree about whether a checkpoint verifies. This file is
 * what makes the format a *name* rather than merely a shape.
 */
describe('the conformance rejections', () => {
  beforeAll(async () => {
    await ready()
  })

  /** A bare natural, which is not a codec of its own anywhere else. */
  const natCodec: Codec<number> = {
    write: (w, n) => w.nat(n),
    read: (r) => r.nat(),
  }

  /** A bare integer, spelled out here so the table below can name it. */
  const bareIntCodec: Codec<bigint> = {
    write: (w, v) => w.int(v),
    read: (r) => r.int(),
  }

  const codecs: Record<Reject['type'], Codec<unknown>> = {
    nat: natCodec as Codec<unknown>,
    int: bareIntCodec as Codec<unknown>,
    string: stringCodec as Codec<unknown>,
    date: dateCodec as Codec<unknown>,
    state: stateCodec as Codec<unknown>,
    event: eventCodec as Codec<unknown>,
  }

  it('ships 17 of them, and every one names a decoder this port has', () => {
    expect(rejects.length).toBe(17)
    for (const x of rejects) {
      expect(x.name).not.toBe('')
      expect(x.description).not.toBe('')
      expect(codecs[x.type]).toBeDefined()
    }
  })

  for (const x of rejects) {
    it(x.name, () => {
      const bs = fromHex(x.hex)
      expect(bs).not.toBeNull()
      expect(() => decode(codecs[x.type], bs as Uint8Array)).toThrow(CodecError)
    })
  }
})
