// Generated by `resources gen-types`. Do not edit.
//
// These types are read off the JSON that the Lean wire encoders actually
// produce, so they cannot drift from the server. Money is always exact
// integer minor units; never parse it as a float.


export interface Amount {
  commodity: string
  exponent: number
  minor: number
  text: string
}

export interface Account {
  closedOn: string | null
  commodity: string | null
  iban: string | null
  id: string
  kind: string
  mine: boolean
  name: string
  note: string | null
  owner: string
  ownerName: string
}

export interface Label {
  colour: string | null
  id: string
  name: string
}

export interface Party {
  email: string | null
  iban: string | null
  id: string
  kind: string
  name: string
  note: string | null
}

export interface Posting {
  account: string
  accountId: string
  amount: Amount
  kind: string
  mine: boolean
  note: string | null
  origin: string
  owner: string
  party: string | null
  tag: string | null
}

export interface Headline {
  account: string
  amount: Amount
}

export interface Transaction {
  attachments: string[]
  balanced: boolean
  date: string
  headline: Headline | null
  id: string
  items: LineItem[] | null
  labels: string[]
  narration: string
  origins: string[]
  payee: string | null
  postings: Posting[]
  source: string
  state: string
}

export interface TransactionPage {
  filter: string
  items: Transaction[]
  limit: number
  offset: number
  total: number
}

export interface Balance {
  account: string
  commodity: string
  minor: number
  text: string
}

export interface StagedEntry {
  amount: Amount
  bankRef: string | null
  batch: string
  counterIban: string | null
  date: string
  fingerprint: string
  id: string
  payee: string | null
  purpose: string | null
  state: string
  suggestedAccount: string | null
  txnId: string | null
}

export interface ImportBatch {
  account: string | null
  at: string
  duplicates: number
  filename: string | null
  id: string
  profile: string
  total: number
}

export interface Attachment {
  bytes: number
  createdAt: string
  mime: string
  origName: string | null
  sha256: string
}

export interface LineItem {
  amount: Amount
  description: string
  id: string
  qty: number
}

export interface Rule {
  addLabels: string[]
  filter: string
  id: string
  name: string
  priority: number
  setAccount: string | null
  setParty: string | null
}

export interface ApiToken {
  createdAt: string
  expiresAt: string | null
  id: string
  lastUsedAt: string | null
  name: string
  scopes: string
}

export interface Revision {
  actor: string
  at: string
  kind: string
  patch: string
  seq: number
}

export interface InvoiceLine {
  description: string
  gross: number
  net: number
  quantity: string
  taxBp: number
  unitPrice: number
}

export interface Invoice {
  budgetId: string
  commodity: string
  due: string
  id: string
  issued: string
  lines: InvoiceLine[]
  net: number
  note: string
  number: string
  payerId: string
  payerName: string
  payment: string
  pendingTxn: string
  reference: string
  settledTxn: string
  sourceAccount: string
  status: string
  tax: number
  total: number
  totalText: string
}

export interface Claim {
  amount: Amount
  due: string
  from: string
  fromAccount: string
  id: string
  labels: unknown[]
  mineToCollect: boolean
  narration: string
  settledBy: string | null
  state: string
  to: string
  toAccount: string
}

export interface Participant {
  account: string
  mine: boolean
  name: string
  owner: string
  weight: number
}

export interface Standing {
  amount: Amount
  name: string
  owes: boolean
  owner: string
}

export interface Budget {
  allocated: Amount
  among: Participant[]
  claims: Claim[]
  closed: boolean
  costs: number
  id: string
  name: string
  note: string
  outstanding: Amount
  shortName: string
  standings: Standing[]
  taken: TakenCost[]
}

export interface TakenCost {
  date: string
  members: string[]
  narration: string
  txn: string
  who: string[]
}

export interface RealmMember {
  id: string
  mine: boolean
  name: string
  role: string
}

export interface Realm {
  admin: boolean
  budget: string | null
  generation: number
  hasKey: boolean
  id: string
  members: RealmMember[]
  name: string
  unverified: boolean
}

export interface RealmMembers {
  granted: string[] | null
  members: RealmMember[]
  name: string
  realm: string
}

export interface Invite {
  expires: string
  for: string
  link: string
  name: string
  realm: string
  role: string
}

export interface Round {
  applied: number
  at: string
  conflicts: number
  pushed: number
  rejected: number
  seq: number
  trouble: string
  unreadable: number
}

export interface SyncStatus {
  boxPk: string
  configured: boolean
  events: number
  hash: string
  lastRound: Round | null
  ledger: string
  member: string
  pending: number
  seq: number
  sequencer: string
  unverified: string[]
}
